CarEnthusiastForumSite/CarEnthusiastForumSite/urls.py
from django.contrib import admin
from django.conf.urls import include
from django.urls import path
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index),
    path('forum/', include('topics.urls')),
    path('account/', include("userprofile.urls")),
]

CarEnthusiastForumSite/topics/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path
from .views import post_create, post_detail, post_list, post_update,comment_thread, deleteComment, PostDelete


app_name = 'topics'
urlpatterns = [
    path('', post_list, name='posts'),
    path('create/', post_create, name='create'),
    path('<int:id>/', post_detail, name='article-detail'),
    path('update/<int:id>/', post_update, name='update'),
    path('comment/<int:id>/', comment_thread, name="thread"),
    path('comment/delete/<int:id>/', deleteComment, name="deleteComment"),

]

CarEnthusiastForumSite/userprofile/urls.py
from django.contrib.auth import logout
from django.urls import path
from . import views

app_name = 'userprofile'

urlpatterns = [
    path('login',views.login_view,name='login'),
    path('logout',views.logout_view,name='logout'),
    path('register',views.register,name = "register"),
]

CarEnthusiastForumSite/topics/models.py
from django.contrib.contenttypes.models import ContentType
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.conf import settings
# Create your models here.


class Topic(models.Model):
    GENERIC = 'GENERIC'
    HELP = 'HELP'
    ADVICE = "ADVICE"
    MYCAR = "MYCAR"
    TIP = "TIP"
    INFORMATIONAL = "INFORMATIONAL"
    TOPIC_OF_POST_CHOISES = (
        (GENERIC, 'Generic'),
        (HELP, 'Help'),
        (ADVICE, 'Advice post'),
        (MYCAR, 'Question about my car'),
        (TIP, 'Tip'),
        (INFORMATIONAL, 'Informational'),
    )
    topic_of_post = models.CharField(choices=TOPIC_OF_POST_CHOISES, default=GENERIC, max_length=100)
    title = models.CharField(null=False, max_length=255)
    approved = models.BooleanField(default=False)
    text_of_post = models.TextField(null=True, max_length = 1024)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)
    likes = models.ManyToManyField(User, related_name="likes", null=True)
    dislikes = models.ManyToManyField(User, related_name="dislikes", null = True)
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)
    created = models.DateTimeField(auto_now=False, auto_now_add=True)


    def __unicode__(self):
        return self.title

    def __str__(self):
        return self.title
    def get_absolute_url(self):
        return reverse("topics:article-detail", kwargs={"id": self.id})

    @property
    def comments(self):
        instance = self,
        id = instance.id
        qs = Comment.objects.filter(post = id)
        return qs




class Comment(models.Model):
    post = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField(null=True, max_length=1024)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)
    likes = models.ManyToManyField(User, related_name="likes_comment")
    dislikes = models.ManyToManyField(User, related_name="dislikes_comment")
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)
    created = models.DateTimeField(auto_now=False, auto_now_add=True)
    parent = models.ForeignKey("self", null=True, blank=True, on_delete=models.CASCADE)

    class Meta:
        ordering = ['-created']

    def __unicode__(self):
        return str(self.created_by.username)

    def __str__(self):
        return str(self.created_by.username)

    def get_absolute_url(self):
        return reverse("topics:thread", kwargs={"id": self.id})

    def get_delete_url(self):
        return reverse("topics:deleteComment", kwargs={"id": self.id})

    def children(self):  # replies
        return Comment.objects.filter(parent=self)

    @property
    def is_parent(self):
        if self.parent is not None:
            return False
        return True

CarEnthusiastForumSite/templates/base.html
<!-- DOCTYPE html-->
<!DOCTYPE html>
<html lang="en">

<head>
<!--  <style>
    body {
  padding-top: 56px;
}
  </style>-->
  {% load static %}
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Car Fan Forum</title>

  <!-- Bootstrap core CSS -->
  <!--<link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">-->

  <!-- Custom styles for this template -->
  <link href="{% static "css/blog-home.css" %}" rel="stylesheet">

</head>

<body>

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
      <a class="navbar-brand" href="#">Welcome to the CF Forum!</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'topics:posts' %}">Posts
              <span class="sr-only">(current)</span>
            </a>
          </li>
            {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'topics:create' %}">Create Post</a>
          </li>
             <li class="nav-item">
            <a class="nav-link" href="{% url 'userprofile:logout' %}">Logout</a>
          </li>
                {% else %}
                <li class="nav-item">
            <a class="nav-link" href="{% url 'userprofile:login' %}">Login</a>
          </li>
            <li class="nav-item">
            <a class="nav-link" href="{% url 'userprofile:register' %}">Register</a>
          </li>
            {% endif %}
          {% comment %}<li class="nav-item">
            <a class="nav-link" href="#">Your Account</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Additional Information</a>
          </li>{% endcomment %}
        </ul>
      </div>
    </div>
  </nav>

  <!-- Page Content -->
  <div class="container">
      <div class="row">

{%block content %}

          {%endblock%}



    </div>
    <!-- /.row -->

  </div>
  <!-- /.container -->

  <!-- Footer -->
<!--  <footer class="py-5 bg-dark">
    <div class="container">
      <p class="m-0 text-center text-white">Copyright &copy; Your Website 2019</p>
    </div>
    &lt;!&ndash; /.container &ndash;&gt;
  </footer>-->

<script   src="http://code.jquery.com/jquery-1.12.2.min.js"   integrity="sha256-lZFHibXzMHo3GGeehn1hudTAP3Sc0uKXBXAzHX1sjtk="   crossorigin="anonymous"></script>


<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>

<script src='https://cdnjs.cloudflare.com/ajax/libs/marked/0.3.5/marked.min.js'></script>
  <script>   src="http://code.jquery.com/jquery-1.12.2.min.js"   integrity="sha256-lZFHibXzMHo3GGeehn1hudTAP3Sc0uKXBXAzHX1sjtk="   crossorigin="anonymous"></script>
<script>

     $(".comment-reply-btn").click(function(event){
        event.preventDefault();
        $(this).parent().next(".comment-reply").fadeToggle();
    })
</script>
</body>

</html>

CarEnthusiastForumSite/templates/comment_thread.html
{% extends "base.html" %}
{% load crispy_forms_tags %}




{% block content %}
{{ object }}



<div class='col-sm-6 col-sm-offset-3'>


          <p>{{ comment.text }}</p>
          <footer>via {{ comment.created_by }} | {{ comment.created|timesince }} ago |
              {% if comment.children.count > 0 %}
                  {{ comment.children.count }} Comment{% if comment.children.count > 1 %}s
                  {% endif %}
              {% endif %}
              {% if request.user == comment.created_by %}
                  <a href='{{ comment.get_delete_url }}'>Delete</a>
              {% endif %}</footer>
          <hr/>
          <div>
              {% for child_comment in comment.children %}
                <blockquote style="margin-left: 20px">
                <p>{{ child_comment.text }}</p>
                <footer>via {{ child_comment.created_by }} | {{ child_comment.created|timesince }} ago | {% if request.user == child_comment.user %}<a href='{{ child_comment.get_delete_url }}'>Delete</a>{% endif %}</footer>
                </blockquote>
             {% endfor %}
             {% if request.user.is_authenticated %}
            <form method="POST" action="."> {% csrf_token %}
                {{ form|crispy }}
                <input type='hidden' name='parent_id' value='{{ comment.id }}'>
                <input type='submit' value='Reply' class='btn btn-success'>
            </form>
            {% else %}
            <p>You must login to comment </p>
            {% endif %}
        </div>



        <hr/>
</div>


{% endblock content %}

CarEnthusiastForumSite/templates/confirm_delete.html
{% extends "base.html" %}
{% load crispy_forms_tags %}




{% block content %}

<div class='col-sm-6 col-sm-offset-3'>
  <h1>Confirm Delete</h1>
        
      
            <form method="POST" action="."> {% csrf_token %}
                <p>Are you sure you want to delete: "{{ object.text }}" ?</p>
              
                <input type='submit' value='Confirm' class='btn btn-warning'>
                <a href='{{ object.get_absolute_url }}' class='btn btn-default'>Cancel</a>
            </form>
        </div>

    

        <hr/>
</div>


{% endblock content %}

CarEnthusiastForumSite/templates/index.html
{% extends 'base.html' %}
{%block content%}
<div class="container-fluid" style="text-align: center">
    <h2>Welcome to the forum</h2>
</div>

{%endblock%}

CarEnthusiastForumSite/templates/login.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
  <div class="container">
    <h1>Login Form</h1>
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
 {{ form|crispy }}
        <input type="submit" class="btn btn-success" value="Login">
    </form>

</div>


{% endblock %}

CarEnthusiastForumSite/templates/logout.html
{% extends "base.html" %}
{% block body %}
<h1>You have logged out </h1>

{% endblock %}

CarEnthusiastForumSite/templates/post_detail.html
{%extends 'base.html'%}
{% block content%}
    {% load crispy_forms_tags %}
 <div class="col-md-12">
  <div class="card-md-12">
  <br>
          <div class="card-body">
            <h2 class="card-title">{{instance.title}}</h2>
            <p class="card-text">{{instance.text_of_post}}</p>
            <!--<a href="#" class="btn btn-primary">Read More &rarr;</a>-->
          </div>
          <div class="card-footer text-muted">
            Posted on {{instance.created}},<br>
              last updated on {{instance.updated}},<br>
              Posted by:  {{instance.created_by}}
            <!--<a href="#">Start Bootstrap</a>-->
          </div>
     <div class="card-footer text-muted">
         {% if request.user == instance.created_by %}
         <a class="btn btn-warning" href="{% url 'topics:update' id=instance.pk %}"> Update Your Post</a>
         {% endif %}
         approved: {{instance.approved}}, dislikes: {{instance.likes.count}} likes: {{instance.dislikes.count}}

     </div>
  </div>
        </div>
    <br>
    <br>
    <div>

        <p class='lead'>Comments</p>
        {% if request.user.is_authenticated %}
        <form method="POST" action="."> {% csrf_token %}
            {{ comment_form|crispy }}
            <input type='submit' value='Post comment' class='btn btn-success'>
        </form>
        {% else %}
        <p>You must login to comment </p>
        {% endif %}
        <hr/>
        {% for comment in comments %}

        <blockquote>
          <p>{{ comment.text }}</p>
          <footer>via {{ comment.created_by }} | {{ comment.created|timesince }} ago | {% if comment.children.count > 0 %}{{ comment.children.count }} Comment{% if comment.children.count > 1 %}s{% endif %} | {% endif %} <a class='comment-reply-btn' href='#'>Reply</a> | <a class='' href='{{ comment.get_absolute_url }}'>Thread</a></footer>
          <div class='comment-reply'>
              {% for child_comment in comment.children %}
                <blockquote style="margin-left: 20px">
                <p>{{ child_comment.text }}</p>
                <footer>via {{ child_comment.created_by }} | {{ child_comment.created|timesince }} ago</footer>
                </blockquote>
             {% endfor %}
             {% if request.user.is_authenticated %}
            <form method="POST" action="."> {% csrf_token %}
                {{ comment_form|crispy }}
                <input type='hidden' name='parent_id' value='{{ comment.id }}'>
                <input type='submit' value='Reply' class='btn btn-success'>
            </form>
            {% else %}
        <p>You must login to comment </p>
        {% endif %}
        </div>

        </blockquote>

        <hr/>
        {% endfor %}
    </div>
{#    <h3>comments:</h3>#}

{%endblock%}

CarEnthusiastForumSite/templates/post_form.html
{% extends "base.html" %}
{% load crispy_forms_tags%}
{% block content %}
<div class='col-sm-6'>
<h1>Create a new Post</h1>
<hr/>

<form method='POST' action='' enctype='multipart/form-data'>{% csrf_token %}
{{ form|crispy }}
<input type='submit' class='btn btn-success' value='Submit' />
</form>
</div>
{% endblock content %}

CarEnthusiastForumSite/templates/post_list.html
{% extends 'base.html' %}

{% block content %}
    <div class="col-md-8">
{% for topic in topic_list %}
<div class="card mb-4">
          <div class="card-body">
            <h2 class="card-title">{{ topic.title }}</h2>
              <a href="{{ topic.get_absolute_url }}" class="btn btn-primary">Read More &rarr;</a>
          </div>
          <div class="card-footer text-muted">
              by {{ topic.created_by }}, Topic: {{ topic.get_topic_of_post_display }}
          </div>
</div>
{% endfor %}
        </div>

    <div class="col-md-4">

        <!-- Search Widget -->
        <div class="card my-4">
          <h5 class="card-header">Search</h5>
          <div class="card-body">
            <div class="input-group">
              <input type="text" class="form-control" placeholder="Search for...">
              <span class="input-group-btn">
                <button class="btn btn-secondary" type="button">Go!</button>
              </span>
            </div>
          </div>
        </div>



        <!-- Categories Widget -->
        <div class="card my-4">
          <h5 class="card-header">Categories</h5>
          <div class="card-body">
            <div class="row">
              <div class="col-lg-6">
                <ul class="list-unstyled mb-0">
                  <li>
                    <a href="#">Generic</a>
                  </li>
                  <li>
                    <a href="#">Help</a>
                  </li>
                  <li>
                    <a href="#">Asking for advice</a>
                  </li>
                </ul>
              </div>
              <div class="col-lg-6">
                <ul class="list-unstyled mb-0">
                  <li>
                    <a href="#">My car</a>
                  </li>
                  <li>
                    <a href="#">Tips</a>
                  </li>
                  <li>
                    <a href="#">Informational</a>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div>
    </div>


{% endblock %}

CarEnthusiastForumSite/templates/register_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container container-fluid">
<form method="post" enctype="multipart/form-data">
  {% csrf_token %}

{{ user_form|crispy }}
<input class="btn btn-success" type="submit" name="" value="Register">

</form>
</div>




{% endblock %}